services:
  app:
    build: .
    networks:
      - tiwap-network
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "mongo:4.4"
    networks:
      - tiwap-network
    environment:
      - MONGO_INITDB_DATABASE=TIWAP
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - "27017:27017"
networks:
  tiwap-network:
    driver: bridge